# Generated by Django 5.0.1 on 2025-08-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adoptions", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoption",
            name="is_temporary_protection",
            field=models.BooleanField(default=False, help_text="임시보호 여부"),
        ),
    ]
