# Generated by Django 5.0.10 on 2025-10-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0004_adoption_is_temporary_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='user_memo',
            field=models.TextField(blank=True, help_text='입양 신청자에 대한 메모', null=True),
        ),
    ]
