# Generated by Django 5.0.10 on 2025-11-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0005_adoption_user_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptioncontract',
            name='center_signature_url',
            field=models.TextField(blank=True, help_text='센터 서명 데이터', null=True),
        ),
        migrations.AlterField(
            model_name='adoptioncontract',
            name='user_signature_url',
            field=models.TextField(blank=True, help_text='사용자 서명 데이터', null=True),
        ),
    ]
