# Generated by Django 5.0.1 on 2025-09-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("adoption_update", "입양 상태 업데이트"),
                    ("monitoring_reminder", "모니터링 알림"),
                    ("center_update", "센터 정보 업데이트"),
                    ("animal_update", "동물 정보 업데이트"),
                    ("system", "시스템 알림"),
                    ("new_adoption_application", "새로운 입양 신청"),
                    ("new_temporary_protection", "새로운 임시보호 등록"),
                    ("monitoring_delayed", "모니터링 지연"),
                    ("adoption_completed", "입양 완료"),
                    ("monitoring_delayed_user", "모니터링 지연 (사용자)"),
                    ("new_comment", "새로운 댓글"),
                    ("new_reply", "새로운 대댓글"),
                    ("other", "기타"),
                ],
                help_text="알림 타입",
                max_length=30,
            ),
        ),
    ]
