# Generated by Django 5.0.1 on 2025-09-05 12:34

from django.db import migrations, models


def migrate_notification_types(apps, schema_editor):
    """기존 알림 유형을 새로운 카테고리로 변환"""
    Notification = apps.get_model('notifications', 'Notification')
    
    type_mapping = {
        # 커뮤니티 관련
        'new_comment': 'community',
        'new_reply': 'community',
        
        # 입양 관련
        'adoption_update': 'adoption',
        'new_adoption_application': 'adoption',
        'new_temporary_protection': 'adoption',
        'adoption_completed': 'adoption',
        
        # 모니터링 관련
        'monitoring_reminder': 'monitoring',
        'monitoring_delayed': 'monitoring',
        'monitoring_delayed_user': 'monitoring',
        
        # 기타
        'center_update': 'other',
        'animal_update': 'other',
        'system': 'other',
        'other': 'other',
    }
    
    for notification in Notification.objects.all():
        old_type = notification.notification_type
        new_type = type_mapping.get(old_type, 'other')
        
        if old_type != new_type:
            notification.notification_type = new_type
            notification.save()
            print(f"알림 유형 변경: {old_type} → {new_type}")


def reverse_migrate_notification_types(apps, schema_editor):
    """역방향 마이그레이션: 새로운 카테고리를 기존 유형으로 복원"""
    # 역방향 매핑은 복잡하므로 기본값으로 설정
    Notification = apps.get_model('notifications', 'Notification')
    
    for notification in Notification.objects.all():
        if notification.notification_type in ['community', 'adoption', 'monitoring', 'other']:
            notification.notification_type = 'other'
            notification.save()


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0007_alter_notification_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="title",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("community", "커뮤니티"),
                    ("adoption", "입양"),
                    ("monitoring", "모니터링"),
                    ("other", "기타"),
                ],
                help_text="알림 타입",
                max_length=30,
            ),
        ),
        # 데이터 마이그레이션 실행
        migrations.RunPython(
            migrate_notification_types,
            reverse_migrate_notification_types,
        ),
    ]
