# Generated by Django 5.0.10 on 2025-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_file',
            field=models.ImageField(blank=True, help_text='배너 이미지 파일', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.CharField(blank=True, help_text='R2 이미지 URL (파일 업로드 시 자동 생성)', max_length=500, null=True),
        ),
    ]
