# Generated by Django 5.0.10 on 2025-10-03 17:38

import banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_banner_image_file_alter_banner_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_file',
            field=models.ImageField(blank=True, help_text='배너 이미지 파일', null=True, upload_to=banners.models.banner_upload_path),
        ),
    ]
