# Generated by Django 5.0.1 on 2025-08-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, help_text="실명", max_length=100, null=True
            ),
        ),
    ]
