# Generated by Django 5.0.10 on 2025-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_memo',
            field=models.TextField(blank=True, help_text='관리자 메모 (입양, 파양 사유 등)', null=True),
        ),
    ]
