# Generated by Django 5.0.10 on 2026-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_admin_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_retention_until',
            field=models.DateTimeField(blank=True, help_text='개인정보 5년 보관 만료 시각 (이후 배치 잡으로 완전 삭제)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='탈퇴 시각 (status=탈퇴유저 시 기록)', null=True),
        ),
    ]
