# Generated by Django 5.0.10 on 2026-05-03 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchoolProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='고유 식별자', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('role', models.CharField(choices=[('user', '일반 사용자'), ('admin', '관리자')], default='user', help_text='강아지학교 권한 (RLS admin 정책 제어용)', max_length=20)),
                ('avatar_url', models.CharField(blank=True, help_text='강아지학교 전용 프로필 이미지 URL (마펫쯔 image와 별개)', max_length=500, null=True)),
                ('user', models.OneToOneField(help_text='연결된 마펫쯔 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '강아지학교 사용자 프로필',
                'verbose_name_plural': '강아지학교 사용자 프로필',
                'db_table': 'user_school_profile',
            },
        ),
    ]
