require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# CocoaPods repositories
source 'https://cdn.cocoapods.org/'
# 카카오 SDK는 기본 CocoaPods 저장소에서 제공됩니다
# source 'https://devrepo.kakao.com/nexus/content/groups/public/'

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  # Kakao SDK
  pod 'KakaoSDK', '~> 2.18.0'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
