"""
Django settings for cfehome project.

Generated by 'django-admin startproject' using Django 5.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import urlparse

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# JWT 서명 전용 키 — 마펫쯔↔강아지학교 통합용 Supabase JWT secret.
# 강아지학교가 PostgREST로 같은 토큰을 stateless 검증하려면 Supabase 프로젝트의
# JWT secret과 동일해야 한다. 미설정 환경(테스트·로컬·통합 전 운영)에서는 SECRET_KEY로
# fallback 하여 기존 동작을 유지한다. Django 세션·CSRF·해시 솔트는 SECRET_KEY 그대로 사용.
JWT_SIGNING_KEY = config("SUPABASE_JWT_SECRET", default="") or SECRET_KEY

# 공공데이터 서비스 키
PUBLIC_DATA_SERVICE_KEY = config("PUBLIC_DATA_SERVICE_KEY", default="")

# 동기화 API 인증 키 (스케줄러 → 동기화 엔드포인트 호출 시 사용, 정부 API 키와 분리)
SYNC_API_KEY = config("SYNC_API_KEY", default="")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = [
    ".mpz.kr",
    "127.0.0.1",
    "localhost",
]

if DEBUG:
    ALLOWED_HOSTS += [
        "127.0.0.1",
        "localhost",
    ]

CSRF_TRUSTED_ORIGINS = [
    "http://*.mpz.kr",
    "https://*.mpz.kr",
]



INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third party
    "corsheaders",
    "channels",
    # local apps
    "common",
    "user",
    "commando",
    "centers",
    "animals",
    "adoptions",
    "comments",
    "favorites",
    "notifications",
    "posts",
    "notices",
    "feedback",
    "banners",
    "storage_service",
    "school",
]

# Email (Naver SMTP)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.naver.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cfehome.urls"

CORS_URLS_REGEX = r"^/v1/.*$"

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = []
ENV_CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", cast=str, default="")
for origin in ENV_CORS_ALLOWED_ORIGINS.split(","):
    raw = origin.strip()
    if not raw:
        continue
    # path가 포함된 경우 django-cors-headers가 에러를 내므로, 스킴+호스트(+포트)만 추출
    parsed = urlparse(raw)
    if parsed.scheme and parsed.netloc:
        cleaned = f"{parsed.scheme}://{parsed.netloc}"
    else:
        # 이미 스킴+호스트 형태라고 가정하고 그대로 사용
        cleaned = raw
    CORS_ALLOWED_ORIGINS.append(cleaned.lower())

# cors & csrf
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = config("SESSION_COOKIE_SAMESITE", default="None")
CSRF_COOKIE_SAMESITE = "None"

# Cookie settings
# 강아지학교(school.mpz.kr)와 쿠키 공유를 위해 운영에서는 `.mpz.kr`로 설정.
# 로컬 개발(localhost)은 빈 값(None)이어야 쿠키가 정상 발급됨 — Makefile의 dev 룰이
# .env에서 SESSION_COOKIE_DOMAIN을 빈 값으로 자동 교체한다.
_session_cookie_domain = config("SESSION_COOKIE_DOMAIN", default="").strip()
SESSION_COOKIE_DOMAIN = _session_cookie_domain or None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 1209600  # 14일

# DJANGO ENVIRONMENT
DJANGO_ENV_NAME = config("DJANGO_ENV_NAME", default=None)

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cfehome.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

CONN_MAX_AGE = config("CONN_MAX_AGE", cast=int, default=300)
DATABASE_URL = config("DATABASE_URL", default=None)

if DATABASE_URL is not None:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=CONN_MAX_AGE,
            conn_health_checks=True,
        ),
    }

if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "user.User"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_BASE_DIR = BASE_DIR / "staticfiles"
STATICFILES_BASE_DIR.mkdir(exist_ok=True, parents=True)
STATICFILES_VENDOR_DIR = STATICFILES_BASE_DIR / "vendors"

STATICFILES_DIRS = [STATICFILES_BASE_DIR]

STATIC_ROOT = BASE_DIR / "local-cdn"
STATIC_ROOT.mkdir(exist_ok=True, parents=True)

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT,
            "base_url": MEDIA_URL,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if DEBUG:
    STORAGES["staticfiles"]["BACKEND"] = "django.contrib.staticfiles.storage.StaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 이미지 업로드 제한 (base64 인코딩 고려, 10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# ninja settings
NINJA_PAGINATION_CLASS = "api.pagination.CustomPageNumberPagination"
PAGINATION_PER_PAGE = 10

# login jwt token expiration
# 강아지학교(stateless PostgREST 검증)와의 logout 갭을 최소화하기 위해 ACCESS는 15분으로
# 단축. 마펫쯔 axios interceptor가 401 시 자동으로 refresh-token으로 재발급한다.
ACCESS_TOKEN_EXPIRATION_TIME = 15  # 15분 (분 단위)
REFRESH_TOKEN_EXPIRATION_TIME = 30 * 24 * 60  # 30일 (분 단위)

# Kakao Social Login Settings
KAKAO_SOCIAL_LOGIN_CLIENT_ID = config("KAKAO_SOCIAL_LOGIN_CLIENT_ID", default="")
KAKAO_SOCIAL_LOGIN_CLIENT_SECRET = config("KAKAO_SOCIAL_LOGIN_CLIENT_SECRET", default="")
NEXT_PUBLIC_KAKAO_REDIRECT_URI = config("NEXT_PUBLIC_KAKAO_REDIRECT_URI", default="")

# Storage Settings (Supabase Storage, S3 호환)
STORAGE_ACCESS_KEY = config("STORAGE_ACCESS_KEY", default="")
STORAGE_SECRET_KEY = config("STORAGE_SECRET_KEY", default="")
STORAGE_BUCKET = config("STORAGE_BUCKET", default="")
STORAGE_ENDPOINT = config("STORAGE_ENDPOINT", default="")
STORAGE_PUBLIC_BASE_URL = config("STORAGE_PUBLIC_BASE_URL", default="")
STORAGE_REGION = config("STORAGE_REGION", default="ap-northeast-2")

FRONTEND_URL = config("FRONTEND_URL", default="http://127.0.0.1:3000")

# OpenAI Settings for AI Features
OPENAI_API_KEY = config("OPENAI_API_KEY", default="")

# LangSmith Settings for LangChain Tracing and Monitoring
LANGCHAIN_TRACING_V2 = config("LANGCHAIN_TRACING_V2", default=False, cast=bool)
LANGCHAIN_PROJECT = config("LANGCHAIN_PROJECT", default="MPZ-AI-Recommendation")
LANGCHAIN_API_KEY = config("LANGCHAIN_API_KEY", default="")
LANGCHAIN_ENDPOINT = config("LANGCHAIN_ENDPOINT", default="https://api.smith.langchain.com")

# Set environment variables for LangSmith if enabled
if LANGCHAIN_TRACING_V2:
    os.environ["LANGCHAIN_TRACING_V2"] = str(LANGCHAIN_TRACING_V2).lower()
    os.environ["LANGCHAIN_PROJECT"] = LANGCHAIN_PROJECT
    if LANGCHAIN_API_KEY:
        os.environ["LANGCHAIN_API_KEY"] = LANGCHAIN_API_KEY
    os.environ["LANGCHAIN_ENDPOINT"] = LANGCHAIN_ENDPOINT

# 알리고 SMS
ALIGO_API_KEY = config("ALIGO_API_KEY", default="")
ALIGO_USER_ID = config("ALIGO_USER_ID", default="")
ALIGO_SENDER = config("ALIGO_SENDER", default="")
ALIGO_TESTMODE = config("ALIGO_TESTMODE", default="N")

# Firebase Admin SDK 초기화
try:
    firebase_path = BASE_DIR / "firebase"
    if firebase_path.exists():
        sys.path.insert(0, str(BASE_DIR))
        import firebase  # noqa: F401
except ImportError:
    pass

# Django Channels Settings
ASGI_APPLICATION = "cfehome.asgi.application"

# Redis / Channels 설정
RAW_REDIS_URL = config("REDIS_URL", default=None)
if RAW_REDIS_URL:
    # channels_redis는 hosts에 list/tuple 형태를 요구하므로 문자열을 리스트로 감싼다
    REDIS_HOSTS = [RAW_REDIS_URL]
else:
    REDIS_HOSTS = None

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": REDIS_HOSTS,
        },
    },
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'INFO',
            'formatter': 'simple',
            'stream': 'ext://sys.stdout',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django.log',
            'level': 'INFO',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # AI 모듈 전용 로거
        'ai.api': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai.services': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai.tools': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # 느린 쿼리 로깅 (느린 쿼리 디버깅 시 level을 DEBUG로 변경)
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}
