# Generated by Django 5.0.1 on 2025-08-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adoptions", "0003_initial"),
        ("animals", "0004_alter_animal_age_alter_animal_weight"),
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postimage",
            options={
                "ordering": ["post", "order_index"],
                "verbose_name": "포스트 이미지",
                "verbose_name_plural": "포스트 이미지들",
            },
        ),
        migrations.RenameField(
            model_name="postimage",
            old_name="sequence",
            new_name="order_index",
        ),
        migrations.RemoveField(
            model_name="post",
            name="comment_count",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="post",
            name="like_count",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_type",
        ),
        migrations.RemoveField(
            model_name="post",
            name="view_count",
        ),
        migrations.RemoveField(
            model_name="postimage",
            name="caption",
        ),
        migrations.AddField(
            model_name="post",
            name="adoption",
            field=models.ForeignKey(
                blank=True,
                help_text="관련 입양",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adoptions.adoption",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                help_text="관련 동물",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="animals.animal",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="content_tags",
            field=models.JSONField(blank=True, help_text="콘텐츠 태그", null=True),
        ),
    ]
