# Generated by Django 5.0.10 on 2025-08-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_systemtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='tag_name',
            field=models.CharField(db_index=True, help_text='태그명', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemtag',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='systemtag',
            name='name',
            field=models.CharField(db_index=True, help_text='태그명', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='posttag',
            index=models.Index(fields=['tag_name'], name='post_tags_tag_nam_ecfe1b_idx'),
        ),
        migrations.AddIndex(
            model_name='posttag',
            index=models.Index(fields=['post', 'tag_name'], name='post_tags_post_id_9a685f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemtag',
            index=models.Index(fields=['name'], name='system_tags_name_05d7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='systemtag',
            index=models.Index(fields=['is_active', 'name'], name='system_tags_is_acti_3fbfe9_idx'),
        ),
        migrations.AddIndex(
            model_name='systemtag',
            index=models.Index(fields=['usage_count'], name='system_tags_usage_c_f31da4_idx'),
        ),
    ]
