# Generated by Django 5.0.1 on 2025-08-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_postlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.IntegerField(default=0, help_text="좋아요 수"),
        ),
    ]
