# Generated by Django 5.0.1 on 2025-08-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_post_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_all_access",
            field=models.BooleanField(
                default=True, help_text="전체 공개 여부 (False인 경우 센터 권한자만 접근 가능)"
            ),
        ),
    ]
