# Generated by Django 5.0.1 on 2025-08-29 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_post_is_all_access"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="adoption",
        ),
    ]
