# Generated by Django 5.0.1 on 2025-08-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0008_alter_animal_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[
                    ("보호중", "보호중"),
                    ("입양대기", "입양대기"),
                    ("입양진행중", "입양진행중"),
                    ("입양완료", "입양완료"),
                    ("안락사", "안락사"),
                    ("자연사", "자연사"),
                    ("반환", "반환"),
                ],
                default="보호중",
                help_text="보호 상태",
                max_length=20,
            ),
        ),
    ]
