# Generated by Django 5.0.1 on 2025-08-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0009_alter_animal_status"),
        ("centers", "0004_center_public_reg_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="is_public_data",
            field=models.BooleanField(default=False, help_text="공공데이터 여부"),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_care_addr",
            field=models.CharField(
                blank=True, help_text="공공데이터 보호소주소", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_care_name",
            field=models.CharField(
                blank=True, help_text="공공데이터 보호소명", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_care_reg_no",
            field=models.CharField(
                blank=True, help_text="공공데이터 보호소번호", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_care_tel",
            field=models.CharField(
                blank=True, help_text="공공데이터 보호소연락처", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_color",
            field=models.CharField(
                blank=True, help_text="공공데이터 색상", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_desertion_number",
            field=models.CharField(
                blank=True, help_text="공공데이터 유기번호", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_happen_date",
            field=models.DateField(blank=True, help_text="공공데이터 구조날짜", null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_happen_place",
            field=models.CharField(
                blank=True, help_text="공공데이터 발견장소", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_kind_code",
            field=models.CharField(
                blank=True, help_text="공공데이터 품종코드", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_notice_number",
            field=models.CharField(
                blank=True, help_text="공공데이터 공고번호 (unique)", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_org_name",
            field=models.CharField(
                blank=True, help_text="공공데이터 기관명", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_special_mark",
            field=models.TextField(blank=True, help_text="공공데이터 특이사항", null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_up_kind_code",
            field=models.CharField(
                blank=True, help_text="공공데이터 축종코드", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="public_update_time",
            field=models.DateTimeField(blank=True, help_text="공공데이터 수정시간", null=True),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["public_notice_number"], name="animals_public__8150c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["is_public_data"], name="animals_is_publ_2ffa41_idx"
            ),
        ),
    ]
