# Generated by Django 5.0.1 on 2025-08-31 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0010_animal_is_public_data_animal_public_care_addr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="public_care_addr",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="public_care_name",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="public_care_reg_no",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="public_care_tel",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="public_color",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="public_desertion_number",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="public_happen_date",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="public_happen_place",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="public_kind_code",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="public_org_name",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="public_special_mark",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="public_up_kind_code",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="public_update_time",
        ),
    ]
