# Generated by Django 5.0.1 on 2025-08-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0011_remove_animal_public_care_addr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="public_notice_number",
            field=models.CharField(
                blank=True,
                help_text="공공데이터 공고번호 (unique)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
