# Generated by Django 5.0.1 on 2025-08-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0012_alter_animal_public_notice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="comment",
            field=models.TextField(blank=True, help_text="공공데이터 특이사항 코멘트", null=True),
        ),
    ]
