# Generated by Django 5.0.1 on 2025-09-05 12:16

from django.db import migrations, models


def migrate_status_to_separate_fields(apps, schema_editor):
    """기존 status 값을 protection_status와 adoption_status로 분리"""
    Animal = apps.get_model('animals', 'Animal')
    
    for animal in Animal.objects.all():
        old_status = animal.status
        
        # 보호 상태 매핑
        if old_status in ['보호중', '안락사', '자연사', '반환']:
            animal.protection_status = old_status
        else:
            animal.protection_status = '보호중'  # 기본값
        
        # 입양 상태 매핑
        if old_status == '입양대기':
            animal.adoption_status = '입양가능'
        elif old_status == '입양진행중':
            animal.adoption_status = '입양진행중'
        elif old_status == '입양완료':
            animal.adoption_status = '입양완료'
        elif old_status in ['안락사', '자연사', '반환']:
            animal.adoption_status = '입양불가'
        else:
            animal.adoption_status = '입양가능'  # 기본값
        
        animal.save()


def reverse_migrate_status(apps, schema_editor):
    """역방향 마이그레이션: protection_status를 status로 복원"""
    Animal = apps.get_model('animals', 'Animal')
    
    for animal in Animal.objects.all():
        # protection_status를 status로 복원
        animal.status = animal.protection_status
        animal.save()


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0013_animal_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="adoption_status",
            field=models.CharField(
                choices=[
                    ("입양가능", "입양가능"),
                    ("입양진행중", "입양진행중"),
                    ("입양완료", "입양완료"),
                    ("입양불가", "입양불가"),
                ],
                default="입양가능",
                help_text="입양 상태",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="protection_status",
            field=models.CharField(
                choices=[("보호중", "보호중"), ("안락사", "안락사"), ("자연사", "자연사"), ("반환", "반환")],
                default="보호중",
                help_text="보호 상태",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[("보호중", "보호중"), ("안락사", "안락사"), ("자연사", "자연사"), ("반환", "반환")],
                default="보호중",
                help_text="보호 상태 (deprecated)",
                max_length=20,
            ),
        ),
        # 데이터 마이그레이션 실행
        migrations.RunPython(
            migrate_status_to_separate_fields,
            reverse_migrate_status,
        ),
    ]
