# Generated by Django 5.0.1 on 2025-09-05 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0014_add_protection_adoption_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="status",
        ),
    ]
