# Generated by Django 5.0.10 on 2025-09-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0015_remove_deprecated_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='notice_end_date',
            field=models.DateField(blank=True, help_text='공고 종료일', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='notice_start_date',
            field=models.DateField(blank=True, help_text='공고 시작일', null=True),
        ),
    ]
