# Generated by Django 5.0.10 on 2025-10-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_animal_notice_end_date_animal_notice_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='trainer_name',
            field=models.CharField(blank=True, help_text='훈련사 이름', max_length=100, null=True),
        ),
    ]
