# Generated by Django 5.0.10 on 2025-10-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0017_animal_trainer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='aggressiveness',
            field=models.PositiveIntegerField(default=3, help_text='사람/강아지 공격성 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='appetite',
            field=models.PositiveIntegerField(default=3, help_text='식욕 왕성함 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='confidence',
            field=models.PositiveIntegerField(default=3, help_text='새로운 자극/상황 적극성 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='coping_ability',
            field=models.PositiveIntegerField(default=3, help_text='낯선 공간 혼자 남겨졌을 때 반응 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='demandingness',
            field=models.PositiveIntegerField(default=3, help_text='무언가 요구할 때 모습 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='dogs_attitude',
            field=models.PositiveIntegerField(default=3, help_text='낯선 강아지 반응 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='environment_attitude',
            field=models.PositiveIntegerField(default=3, help_text='낯선 환경 반응 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='excitability',
            field=models.PositiveIntegerField(default=3, help_text='일상 상황 호흡/심박/꼬리 움직임 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='grooming_acceptance_level',
            field=models.PositiveIntegerField(default=3, help_text='그루밍 진행 시 모습 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='handling_acceptance',
            field=models.PositiveIntegerField(default=3, help_text='몸 만지기 저항감 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='independence',
            field=models.PositiveIntegerField(default=3, help_text='독립성 있는 행동 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='objects_attitude',
            field=models.PositiveIntegerField(default=3, help_text='낯선 사물 반응 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='physical_contact',
            field=models.PositiveIntegerField(default=3, help_text='사람 터치 긍정적 수용 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='playfulness_level',
            field=models.PositiveIntegerField(default=3, help_text='장난감/바디시그널 놀이 유도 반응 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='possessiveness',
            field=models.PositiveIntegerField(default=3, help_text='소유물 지키기 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='resilience',
            field=models.PositiveIntegerField(default=3, help_text='불편한 경험 후 회복력 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='strangers_attitude',
            field=models.PositiveIntegerField(default=3, help_text='낯선 사람 반응 (1-5)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='walkability_level',
            field=models.PositiveIntegerField(default=3, help_text='산책 과정에서 모습 (1-5)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='activity_level',
            field=models.PositiveIntegerField(default=3, help_text='활동량 수준 (1-5)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='basic_training',
            field=models.PositiveIntegerField(default=3, help_text='기본 훈련 상태 (1-5)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sensitivity',
            field=models.PositiveIntegerField(default=3, help_text='예민함 정도 (1-5)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='separation_anxiety',
            field=models.PositiveIntegerField(default=3, help_text='분리불안 정도 (1-5)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sociability',
            field=models.PositiveIntegerField(default=3, help_text='사회성 (1-5)'),
        ),
    ]
