# Generated by Django 5.0.10 on 2025-10-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0018_animal_aggressiveness_animal_appetite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='aggressiveness',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='appetite',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='demandingness',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='excitability',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='possessiveness',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='resilience',
        ),
    ]
