# Generated by Django 5.0.10 on 2025-10-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0019_remove_animal_aggressiveness_remove_animal_appetite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='basic_training',
        ),
    ]
