# Generated by Django 5.0.10 on 2025-10-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0020_remove_animal_basic_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='protection_status',
            field=models.CharField(choices=[('보호중', '보호중'), ('임시보호', '임시보호'), ('안락사', '안락사'), ('자연사', '자연사'), ('반환', '반환'), ('기증', '기증'), ('방사', '방사'), ('입양완료', '입양완료')], default='보호중', help_text='보호 상태', max_length=20),
        ),
    ]
