# Generated by Django 5.0.10 on 2025-11-16 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0021_alter_animal_protection_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='고유 식별자', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('approved', '승인'), ('rejected', '거절'), ('cancelled', '취소')], default='pending', help_text='신청 상태', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True, help_text='신청일')),
                ('approval_date', models.DateTimeField(blank=True, help_text='승인/거절일', null=True)),
                ('reason', models.TextField(blank=True, help_text='입양 사유', null=True)),
                ('contact_phone', models.CharField(help_text='연락처', max_length=20)),
                ('contact_email', models.EmailField(help_text='이메일', max_length=254)),
                ('home_address', models.CharField(help_text='거주지', max_length=200)),
                ('family_size', models.PositiveIntegerField(default=1, help_text='가족 구성원 수')),
                ('has_pet_experience', models.BooleanField(default=False, help_text='반려동물 양육 경험')),
                ('can_visit_center', models.BooleanField(default=True, help_text='센터 방문 가능 여부')),
                ('admin_notes', models.TextField(blank=True, help_text='관리자 코멘트', null=True)),
                ('animal', models.ForeignKey(help_text='입양 희망 동물', on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('processed_by', models.ForeignKey(blank=True, help_text='처리 담당자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='신청자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '입양 신청',
                'verbose_name_plural': '입양 신청들',
                'db_table': 'adoption_applications',
                'indexes': [models.Index(fields=['status'], name='adoption_ap_status_dccb85_idx'), models.Index(fields=['application_date'], name='adoption_ap_applica_915034_idx'), models.Index(fields=['animal', 'status'], name='adoption_ap_animal__8e854a_idx')],
                'unique_together': {('user', 'animal')},
            },
        ),
    ]
