# Generated by Django 5.0.1 on 2025-08-24 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "피드백",
                "verbose_name_plural": "피드백들",
            },
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="feedback_type",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="title",
        ),
        migrations.AddField(
            model_name="feedback",
            name="responded_at",
            field=models.DateTimeField(blank=True, help_text="답변 시간", null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                help_text="답변한 관리자",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responded_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="content",
            field=models.TextField(help_text="피드백 내용"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="priority",
            field=models.CharField(
                choices=[("낮음", "낮음"), ("보통", "보통"), ("높음", "높음"), ("긴급", "긴급")],
                default="보통",
                help_text="피드백 우선순위",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("접수", "접수"),
                    ("검토중", "검토중"),
                    ("처리중", "처리중"),
                    ("보류", "보류"),
                    ("완료", "완료"),
                ],
                default="접수",
                help_text="피드백 상태",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="사용자 (로그인한 경우)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="feedback",
            table="feedbacks",
        ),
    ]
