# Generated by Django 5.0.1 on 2025-08-20 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdoptionContractTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("title", models.CharField(help_text="계약서 제목", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="계약서 설명/목적", null=True),
                ),
                ("content", models.TextField(help_text="계약서 본문 내용")),
                ("is_active", models.BooleanField(default=True, help_text="활성화 여부")),
            ],
            options={
                "verbose_name": "입양 계약서 템플릿",
                "verbose_name_plural": "입양 계약서 템플릿들",
                "db_table": "adoption_contract_templates",
            },
        ),
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("name", models.CharField(help_text="센터명", max_length=100)),
                (
                    "center_number",
                    models.CharField(
                        blank=True, help_text="보호소 번호", max_length=20, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="센터 설명", null=True),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="위치", max_length=200, null=True
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            # 두 글자 형식 (기존 호환성)
                            ("서울", "서울"),
                            ("부산", "부산"),
                            ("대구", "대구"),
                            ("인천", "인천"),
                            ("광주", "광주"),
                            ("대전", "대전"),
                            ("울산", "울산"),
                            ("세종", "세종"),
                            ("경기", "경기"),
                            ("강원", "강원"),
                            ("충북", "충북"),
                            ("충남", "충남"),
                            ("전북", "전북"),
                            ("전남", "전남"),
                            ("경북", "경북"),
                            ("경남", "경남"),
                            ("제주", "제주"),
                            # 전체 이름 형식 (공공데이터 호환)
                            ("서울특별시", "서울특별시"),
                            ("부산광역시", "부산광역시"),
                            ("대구광역시", "대구광역시"),
                            ("인천광역시", "인천광역시"),
                            ("광주광역시", "광주광역시"),
                            ("대전광역시", "대전광역시"),
                            ("울산광역시", "울산광역시"),
                            ("세종특별자치시", "세종특별자치시"),
                            ("세종특별시", "세종특별시"),
                            ("경기도", "경기도"),
                            ("강원도", "강원도"),
                            ("강원특별자치도", "강원특별자치도"),
                            ("충청북도", "충청북도"),
                            ("충청남도", "충청남도"),
                            ("전라북도", "전라북도"),
                            ("전북특별자치도", "전북특별자치도"),
                            ("전라남도", "전라남도"),
                            ("경상북도", "경상북도"),
                            ("경상남도", "경상남도"),
                            ("제주특별자치도", "제주특별자치도"),
                        ],
                        help_text="지역",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="전화번호", max_length=20, null=True
                    ),
                ),
                (
                    "adoption_procedure",
                    models.TextField(blank=True, help_text="입양 절차", null=True),
                ),
                (
                    "adoption_guidelines",
                    models.TextField(blank=True, help_text="입양 유의사항", null=True),
                ),
                (
                    "has_monitoring",
                    models.BooleanField(default=False, help_text="모니터링 실시 여부"),
                ),
                (
                    "monitoring_period_months",
                    models.IntegerField(default=3, help_text="모니터링 전체 기간 (개월)"),
                ),
                (
                    "monitoring_interval_days",
                    models.IntegerField(default=14, help_text="모니터링 체크 간격 (일)"),
                ),
                (
                    "monitoring_description",
                    models.TextField(blank=True, help_text="모니터링 방법/설명", null=True),
                ),
                ("verified", models.BooleanField(default=False, help_text="인증 여부")),
                ("is_public", models.BooleanField(default=False, help_text="공개 여부")),
                ("adoption_price", models.IntegerField(default=0, help_text="입양 가격")),
                (
                    "image_url",
                    models.CharField(
                        blank=True, help_text="센터 이미지 URL", max_length=500, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "센터",
                "verbose_name_plural": "센터들",
                "db_table": "centers",
            },
        ),
        migrations.CreateModel(
            name="QuestionForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("question", models.TextField(help_text="질문 내용")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "텍스트"),
                            ("textarea", "긴 텍스트"),
                            ("radio", "라디오"),
                            ("checkbox", "체크박스"),
                            ("select", "선택"),
                        ],
                        help_text="질문 타입",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(blank=True, help_text="선택지 옵션들", null=True),
                ),
                ("is_required", models.BooleanField(default=False, help_text="필수 여부")),
                ("sequence", models.IntegerField(default=1, help_text="질문 순서")),
            ],
            options={
                "verbose_name": "질문 폼",
                "verbose_name_plural": "질문 폼들",
                "db_table": "question_forms",
                "ordering": ["center", "sequence"],
            },
        ),
    ]
