# Generated by Django 5.0.1 on 2025-08-31 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centers", "0003_remove_questionform_question_type_questionform_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="public_reg_no",
            field=models.CharField(
                blank=True,
                help_text="공공데이터 보호소번호",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="center",
            index=models.Index(
                fields=["public_reg_no"], name="centers_public__785cb8_idx"
            ),
        ),
    ]
