# Generated by Django 5.0.10 on 2025-09-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_remove_questionform_question_type_questionform_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='구독 여부'),
        ),
    ]
