# Generated by Django 5.0.1 on 2025-08-31 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centers", "0004_center_public_reg_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "code",
                    models.CharField(help_text="시도 코드", max_length=10, unique=True),
                ),
                ("name", models.CharField(help_text="시도명", max_length=50)),
            ],
            options={
                "verbose_name": "시도",
                "verbose_name_plural": "시도들",
                "db_table": "sidos",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Sigungu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "code",
                    models.CharField(help_text="시군구 코드", max_length=10, unique=True),
                ),
                ("name", models.CharField(help_text="시군구명", max_length=50)),
                (
                    "sido",
                    models.ForeignKey(
                        help_text="상위 시도",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centers.sido",
                    ),
                ),
            ],
            options={
                "verbose_name": "시군구",
                "verbose_name_plural": "시군구들",
                "db_table": "sigungus",
                "ordering": ["sido__code", "code"],
            },
        ),
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "care_reg_no",
                    models.CharField(help_text="보호소 등록번호", max_length=50, unique=True),
                ),
                ("care_nm", models.CharField(help_text="보호소명", max_length=200)),
                (
                    "care_tel",
                    models.CharField(
                        blank=True, help_text="보호소 연락처", max_length=50, null=True
                    ),
                ),
                (
                    "care_addr",
                    models.CharField(
                        blank=True, help_text="보호소 주소", max_length=500, null=True
                    ),
                ),
                (
                    "care_owner_nm",
                    models.CharField(
                        blank=True, help_text="보호소 소유자명", max_length=100, null=True
                    ),
                ),
                (
                    "org_nm",
                    models.CharField(
                        blank=True, help_text="기관명", max_length=200, null=True
                    ),
                ),
                (
                    "sido",
                    models.ForeignKey(
                        blank=True,
                        help_text="소재 시도",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="centers.sido",
                    ),
                ),
                (
                    "sigungu",
                    models.ForeignKey(
                        blank=True,
                        help_text="소재 시군구",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="centers.sigungu",
                    ),
                ),
            ],
            options={
                "verbose_name": "보호소",
                "verbose_name_plural": "보호소들",
                "db_table": "shelters",
                "ordering": ["care_nm"],
            },
        ),
    ]
