# Generated by Django 5.0.1 on 2025-08-31 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("centers", "0005_sido_sigungu_shelter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sigungu",
            name="sido",
        ),
        migrations.DeleteModel(
            name="Shelter",
        ),
        migrations.DeleteModel(
            name="Sido",
        ),
        migrations.DeleteModel(
            name="Sigungu",
        ),
    ]
