# Generated by Django 5.0.10 on 2025-09-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_center_is_subscribed'),
        ('centers', '0006_remove_sigungu_sido_delete_shelter_delete_sido_and_more'),
    ]

    operations = [
    ]
