# Generated by Django 5.0.1 on 2025-09-03 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centers", "0007_merge_20250901_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="has_foster_care",
            field=models.BooleanField(default=False, help_text="임시보호 여부"),
        ),
        migrations.AddField(
            model_name="center",
            name="has_volunteer",
            field=models.BooleanField(default=False, help_text="봉사활동 여부"),
        ),
        migrations.AddField(
            model_name="center",
            name="show_location",
            field=models.BooleanField(default=True, help_text="위치 노출 여부"),
        ),
        migrations.AddField(
            model_name="center",
            name="show_phone_number",
            field=models.BooleanField(default=True, help_text="전화번호 노출 여부"),
        ),
        migrations.CreateModel(
            name="AdoptionConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("title", models.CharField(help_text="동의서 제목", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="동의서 설명/목적", null=True),
                ),
                ("content", models.TextField(help_text="동의서 본문 내용")),
                ("is_active", models.BooleanField(default=True, help_text="활성화 여부")),
                (
                    "center",
                    models.ForeignKey(
                        help_text="관련 센터",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centers.center",
                    ),
                ),
            ],
            options={
                "verbose_name": "입양 동의서",
                "verbose_name_plural": "입양 동의서들",
                "db_table": "adoption_consents",
            },
        ),
    ]
