# Generated by Django 5.0.10 on 2025-10-31 01:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0009_center_call_available_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='고유 식별자', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('category', models.CharField(choices=[('lifeEnvironment', '생활 환경'), ('experience', '반려 경험'), ('responsibility', '책임과 계획')], help_text='질문 카테고리', max_length=20)),
                ('question', models.TextField(help_text='질문 내용')),
                ('sequence', models.IntegerField(default=1, help_text='질문 순서')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
            ],
            options={
                'verbose_name': '기본 질문',
                'verbose_name_plural': '기본 질문들',
                'db_table': 'preset_questions',
                'ordering': ['category', 'sequence'],
            },
        ),
    ]
