# Generated by Django 5.0.10 on 2025-11-16 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0010_presetquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='고유 식별자', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('title', models.CharField(help_text='동의서 제목', max_length=200)),
                ('description', models.TextField(blank=True, help_text='동의서 설명/목적', null=True)),
                ('content', models.TextField(help_text='동의서 본문 내용')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
            ],
            options={
                'verbose_name': '기본 동의서',
                'verbose_name_plural': '기본 동의서들',
                'db_table': 'preset_consents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresetContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='고유 식별자', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('title', models.CharField(help_text='계약서 제목', max_length=200)),
                ('description', models.TextField(blank=True, help_text='계약서 설명/목적', null=True)),
                ('content', models.TextField(help_text='계약서 본문 내용')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
            ],
            options={
                'verbose_name': '기본 계약서 템플릿',
                'verbose_name_plural': '기본 계약서 템플릿들',
                'db_table': 'preset_contract_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
