# Generated by Django 5.0.10 on 2026-04-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0011_presetconsent_presetcontracttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center_type',
            field=models.CharField(choices=[('private', '민간'), ('public', '공공')], default='public', help_text='센터 유형 (민간/공공)', max_length=10),
        ),
    ]
